from typing import Protocol

class VMSAdapter(Protocol):
    async def authenticate(self) -> None: ...
    async def get_cameras(self) -> list[dict]: ...
    async def get_stream(self, camera_id: str) -> dict: ...
    async def get_recording(self, camera_id: str, start: str, end: str) -> dict: ...
